name: Testing workflow variables

on:
  workflow_dispatch:

env:
  cloud: google-cloud

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "say Hello Brahma it's Monday"
        run: echo "$Greeting $First_Name is using $cloud"
        env:
          First_Name: Brahma
